<?php

// Variáveis com os títulos
$titulos = array(
    'Tipo de registro',
    'Código de escola - Inep',
    'Código da pessoa física no sistema próprio',
    'Identificação única (Inep)',
    'Número do CPF',
    'Nome completo',
    'Data de nascimento',
    'Filiação',
    'Filiação 1 (preferencialmente o nome da mãe)',
    'Filiação 2 (preferencialmente o nome do pai)',
    'Sexo',
    'Cor/Raça',
    'Nacionalidade',
    'País de nacionalidade',
    'Município de nascimento',
    'Deficiência, transtorno do espectro autista ou altas habilidades/superdotação',
    'Pessoa física com deficiência, transtorno do espectro autista ou altas habilidades/superdotação',
    'Tipo de deficiência, transtorno do espectro autista e altas habilidades/superdotação',
    'Cegueira',
    'Baixa visão',
    'Visão monocular',
    'Surdez',
    'Deficiência auditiva',
    'Surdocegueira',
    'Deficiência física',
    'Deficiência intelectual',
    'Deficiência múltipla',
    'Transtorno do espectro autista',
    'Altas habilidades/superdotação',
    'Recursos para uso do(a) aluno(a) em sala de aula e para participação em avaliações do Inep (Saeb)',
    'Auxílio ledor',
    'Auxílio transcrição',
    'Guia-Intérprete',
    'Tradutor-Intérprete de Libras',
    'Leitura Labial',
    'Prova Ampliada (Fonte 18)',
    'Prova superampliada (Fonte 24)',
    'CD com áudio para deficiente visual',
    'Prova de Língua Portuguesa como Segunda Língua para surdos e deficientes auditivos',
    'Prova em Vídeo em Libras',
    'Material didático e prova em Braille',
    'Nenhum',
    'Número da matrícula da certidão de nascimento (certidão nova)',
    'País de residência',
    'CEP',
    'Município de residência',
    'Localização/ Zona de residência',
    'Localização diferenciada de residência',
    'Maior nível de escolaridade concluído',
    'Tipo de ensino médio cursado',
    'Código do Curso 1',
    'Ano de Conclusão 1',
    'Instituição de educação superior 1',
    'Código do Curso 2',
    'Ano de Conclusão 2',
    'Instituição de educação superior 2',
    'Código do Curso 3',
    'Ano de Conclusão 3',
    'Instituição de educação superior 3',
    'Formação/Complementação pedagógica Área do conhecimento/componentes curriculares 1',
    'Área do conhecimento/componentes curriculares 2',
    'Área do conhecimento/componentes curriculares 3',
    'Pós-Graduações concluídas',
    'Tipo de pós-graduação 1',
    'Área da pós-graduação 1',
    'Ano de conclusão da pós-graduação 1',
    'Tipo de pós-graduação 2',
    'Área da pós-graduação 2',
    'Ano de conclusão da pós-graduação 2',
    'Tipo de pós-graduação 3',
    'Área da pós-graduação 3',
    'Ano de conclusão da pós-graduação 3',
    'Tipo de pós-graduação 4',
    'Área da pós-graduação 4',
    'Ano de conclusão da pós-graduação 4',
    'Tipo de pós-graduação 5',
    'Área da pós-graduação 5',
    'Ano de conclusão da pós-graduação 5',
    'Tipo de pós-graduação 6',
    'Área da pós-graduação 6',
    'Ano de conclusão da pós-graduação 6',
    'Não tem pós-graduação concluída',
    'Outros cursos específicos (Formação continuada com mínimo de 80 horas)',
    'Creche (0 a 3 anos)',
    'Pré-escola (4 e 5 anos)',
    'Anos iniciais do ensino fundamental',
    'Anos finais do ensino fundamental',
    'Ensino médio',
    'Educação de jovens e adultos',
    'Educação especial',
    'Educação Indígena',
    'Educação do campo',
    'Educação ambiental',
    'Educação em direitos humanos',
    'Educação bilíngue de surdos',
    'Educação e Tecnologia de Informação e Comunicação (TIC)',
    'Gênero e diversidade sexual',
    'Direitos de criança e adolescente',
    'Educação para as relações étnico-raciais e História e cultura afro-brasileira e africana',
    'Gestão Escolar',
    'Outros',
    'Nenhum',
    'Endereço Eletrônico (e-mail)'
);

// Conteúdo das variáveis
$conteudo = array(
    'tipo_de_registro',
    'codigo_escola_inep',
    'codigo_pessoa_fisica',
    'identificacao_inep',
    'numero_cpf',
    'nome_completo',
    'data_nascimento',
    'filiacao',
    'filiacao1',
    'filiacao2',
    'sexo',
    'cor_raca',
    'nacionalidade',
    'pais_nacionalidade',
    'municipio_nascimento',
    'deficiencia_transtorno',
    'pessoa_com_deficiencia',
    'tipo_deficiencia',
    'cegueira',
    'baixa_visao',
    'visao_monocular',
    'surdez',
    'deficiencia_auditiva',
    'surdocegueira',
    'deficiencia_fisica',
    'deficiencia_intelectual',
    'deficiencia_multipla',
    'transtorno_autista',
    'altas_habilidades',
    'recursos_saeb',
    'auxilio_ledor',
    'auxilio_transcricao',
    'guia_interprete',
    'tradutor_libras',
    'leitura_labial',
    'prova_ampliada',
    'prova_superampliada',
    'cd_audio',
    'prova_libras',
    'material_braille',
    'nenhum_recursos',
    'numero_matricula',
    'pais_residencia',
    'cep',
    'municipio_residencia',
    'localizacao_residencia',
    'localizacao_diferenciada',
    'nivel_escolaridade',
    'tipo_ensino_medio',
    'codigo_curso1',
    'ano_conclusao1',
    'instituicao_ensino1',
    'codigo_curso2',
    'ano_conclusao2',
    'instituicao_ensino2',
    'codigo_curso3',
    'ano_conclusao3',
    'instituicao_ensino3',
    'formacao_pedagogica1',
    'formacao_pedagogica2',
    'formacao_pedagogica3',
    'posgrad_tipo1',
    'posgrad_area1',
    'posgrad_conclusao1',
    'posgrad_tipo2',
    'posgrad_area2',
    'posgrad_conclusao2',
    'posgrad_tipo3',
    'posgrad_area3',
    'posgrad_conclusao3',
    'posgrad_tipo4',
    'posgrad_area4',
    'posgrad_conclusao4',
    'posgrad_tipo5',
    'posgrad_area5',
    'posgrad_conclusao5',
    'posgrad_tipo6',
    'posgrad_area6',
    'posgrad_conclusao6',
    'sem_posgrad',
    'outros_cursos',
    'creche',
    'pre_escola',
    'ensino_fundamental_iniciais',
    'ensino_fundamental_finais',
    'ensino_medio',
    'educacao_jovens_adultos',
    'educacao_especial',
    'educacao_indigena',
    'educacao_campo',
    'educacao_ambiental',
    'educacao_direitos_humanos',
    'educacao_bilingue',
    'educacao_tic',
    'genero_diversidade',
    'direitos_crianca_adolescente',
    'educacao_relacoes_etnico_raciais',
    'gestao_escolar',
    'outros_educacao',
    'nenhum_educacao',
    'email'
);

// ... Seu código anterior ...

// Criação do arquivo de texto
$file = fopen('dados.txt', 'w');

// Escreve os títulos no arquivo
foreach ($titulos as $titulo) {
    fwrite($file, $titulo . "\t");
}

fwrite($file, "\n");

// Escreve o conteúdo das variáveis no arquivo
foreach ($conteudo as $var) {
    fwrite($file, $$var . "|\t");
}

fclose($file);

// Define o tipo de conteúdo como um arquivo de texto
header('Content-Type: text/plain');

// Define o cabeçalho Content-Disposition para fazer o download
header('Content-Disposition: attachment; filename="dados.txt"');

// Lê o arquivo e o envia para a saída
readfile('dados.txt');

// Remove o arquivo após o download
unlink('dados.txt');

?>
